resolver: lts-6.4
packages:
- '.'
- '../shared/'
- location:
    git: git@github.com:reflex-frp/reflex
    commit: 91299fce0bb2caddfba35af6608df57dd31e3690
  extra-dep: true
- location:
    git: git@github.com:reflex-frp/reflex-dom
    commit: 66b6d35773fcb337ab38ebce02c4b23baeae721e
  extra-dep: true

extra-deps:
  - aeson-injector-1.0.6.0
  - haskell-src-exts-1.16.0.1
  - servant-auth-token-0.3.2.0
  - servant-auth-token-api-0.3.2.0
  - ref-tf-0.4
  - hlint-1.9.35
  - prim-uniq-0.1.0.1
  - zenc-0.1.1
  - keycode-0.2.2
  - async-2.1.1
flags: {}
extra-package-dbs: []
compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
        sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3
