resolver: lts-7.14

# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
# - location:
#    git: https://github.com/commercialhaskell/stack.git
#    commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
# - location: https://github.com/commercialhaskell/stack/commit/e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#   extra-dep: true
#  subdirs:
#  - auto-update
#  - wai
#
# A package marked 'extra-dep: true' will only be built if demanded by a
# non-dependency (i.e. a user package), and its test suites and benchmarks
# will not be run. This is useful for tweaking upstream packages.
packages:
- backend/
- shared/

extra-deps:
- HUnit-1.3.1.2
- aeson-0.11.2.1
- esqueleto-2.4.3
- hspec-2.2.4
- hspec-core-2.2.4
- hspec-discover-2.2.4
- hspec-expectations-0.7.2
- http-api-data-0.2.4
- logging-effect-1.1.1
- insert-ordered-containers-0.1.0.1
- persistent-2.2.4.1
- persistent-postgresql-2.2.2
- persistent-template-2.1.8.1
- servant-0.8.1
- servant-auth-token-0.3.2.0
- servant-auth-token-api-0.3.2.0
- servant-client-0.8.1
- servant-docs-0.8.1
- servant-quickcheck-0.0.2.2
- servant-server-0.8.1

flags: {}
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.3"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
