name: backend
version: 0.1.0
synopsis: rsvp event system
description: Please see README.md
maintainer: tippenein <tippenein@gmail.com>
license: Apache
github: tippenein/rsvp
category: Web

ghc-options: -Wall -Werror
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards

dependencies:
  - base >= 4.9 && < 5
  - protolude

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - esqueleto
    - exceptions
    - http-media
    - http-types
    - logging-effect
    - monad-logger
    - mtl
    - optparse-applicative
    - prometheus-client
    - prometheus-metrics-ghc
    - persistent
    - persistent-postgresql
    - persistent-template
    - servant
    - servant-server
    - text
    - time
    - transformers
    - wai
    - wai-extra
    - wai-cors
    - wai-middleware-prometheus
    - warp
    - wl-pprint-text
    - http-media
    - neat-interpolation

executables:
  rsvp:
    main: Main.hs
    source-dirs: cmd
    dependencies:
      - backend

tests:
  rsvp-api-tests:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - backend
      - logging-effect
      - QuickCheck
      - quickcheck-instances
      - servant-quickcheck
      - tasty
      - tasty-hspec
