name: rsvp-api
version: 0.1.0
synopsis: rsvp event system
description: Please see README.md
maintainer: tippenein <tippenein@gmail.com>
license: Apache
github: tippenein/rsvp
category: Web

ghc-options: -Wall -Werror
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards

dependencies:
  - base >= 4.9 && < 5
  - protolude

library:
  source-dirs: src
  dependencies:
    - aeson
    - http-media
    - neat-interpolation
    - servant

tests:
  rsvp-api-tests:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - rsvp-api
      - tasty
